### ISSUE TITLE
TS_NODE_IGNORE is not passed

### ISSUE THREAD

**Issue by testerez** [whitecolor/ts-node-dev#5]
Hello,

I just tried to change `nodemon` for `ts-node-dev` but it's not working for me.
I get this error: `SyntaxError: Unexpected token import`

My guess is that it's coming from `lodash-es`. I used to solve this issue by adding the env variable `TS_NODE_IGNORE= '/node_modules/(?!lodash-es/.*)'` it's working with `nodemon` but not `ts-node-dev`

I also tried: 
```
ts-node-dev -F --ignore '/node_modules/(?!lodash-es/.*)' ./src/server/index.ts
```
(same result)

**Comment by whitecolor** [comment]
Try to use `--ignore-watch` switch, see in readme.

**Comment by testerez** [comment]
Thanks @whitecolor but it does not solve my issue.

Note that what I need it to override the `ts-node`'s default ignore setting so
`/node_modules/lodash-es/.*)` is processed by tsc. It's not related to watch.

**Comment by whitecolor** [comment]
Are you sure that the error comes from typescript compilation? Currently by default actually all files that in are `/node_modules/` ignored. Are you using `allowJs` option?

**Comment by testerez** [comment]
No I think that the error comes from the execution because `/node_modules/lodash-es/.*` is not processed by tsc so the `imports` it contains are not transpiled to `require`.
Yes I use `allowJs`.

**Comment by whitecolor** [comment]
I've published updated version, check if it works for you.

**Comment by testerez** [comment]
Thanks!
`--ignore` seams to work but not `TS_NODE_IGNORE` env variable has no effect.

Also I say "seams" because I have another error now:
```
[1] Error: Could not require /Users/tomesterez/projects/pbv4/src/icons/generated/index.ts, compiled path:/var/folders/4x/gp6ghhk16lndwzb52gkf6b080000gp/T/.ts-node/compiled/src_icons_generated_index_ts_74e7673fb0e62134b00a7fa45129c3fcb485b157a83b428c7da05edb3a4e6114.js
[1]     at compile (/private/var/folders/4x/gp6ghhk16lndwzb52gkf6b080000gp/T/ts-node-dev-hook-1518375486465.js:27:13)
[1]     at Module.m._compile (/private/var/folders/4x/gp6ghhk16lndwzb52gkf6b080000gp/T/ts-node-dev-hook-1518375486465.js:41:36)
[1]     at Module._extensions..js (module.js:671:10)
[1]     at require.extensions.(anonymous function) (/private/var/folders/4x/gp6ghhk16lndwzb52gkf6b080000gp/T/ts-node-dev-hook-1518375486465.js:43:14)
[1]     at Object.nodeDevHook [as .ts] (/Users/tomesterez/projects/pbv4/node_modules/ts-node-dev/lib/hook.js:61:7)
[1]     at Module.load (module.js:573:32)
[1]     at tryModuleLoad (module.js:513:12)
[1]     at Function.Module._load (module.js:505:3)
[1]     at Function.wrappedLoad [as _load] (/Users/tomesterez/projects/pbv4/node_modules/newrelic/lib/shimmer.js:344:38)
[1]     at Module.require (module.js:604:17)
[1] [ERROR] 13:58:31 Error: Could not require /Users/tomesterez/projects/pbv4/src/icons/generated/index.ts, compiled path:/var/folders/4x/gp6ghhk16lndwzb52gkf6b080000gp/T/.ts-node/compiled/src_icons_generated_index_ts_74e7673fb0e62134b00a7fa45129c3fcb485b157a83b428c7da05edb3a4e6114.js
```

Probably not related. Any idea what could be the issue?

**Comment by whitecolor** [comment]
Well, I think `TS_NODE_IGNORE` should work if `--ignore` option not passed this just takes `process.env['TS_NODE_IGNORE']`, I checked it works for me.

Aso for `Could not require` I saw this error too sometimes, but I just can not get how to reproduce it.
But I update to latest published version now, see if you get this error with it. It would be very helpful if you know how to reproduce it.

**Comment by testerez** [comment]
Not sure why but `TS_NODE_IGNORE` does not work for me. `--ignore` does.
I'm also still getting the `Could not require` error. I have no idea what's the issue.
What I can tell:
- The file causing the issue is 106KB which is pretty big
- The compiled path leads to a valid file that includes inline sourcemap
- I have `"allowJs": true`. I need it but the file causing the issue is `ts` not `js`. Might be related to https://github.com/whitecolor/ts-node-dev/issues/1

**Comment by testerez** [comment]
I just saw https://github.com/whitecolor/ts-node-dev/issues/6 that already reports the `Could not require`
So I guess this issue should focus on `TS_NODE_IGNORE` not being passed.

**Comment by whitecolor** [comment]
Btw I checked once again if `TS_NODE_IGNORE` presents in `process.env` it should work. Not sure why it doesn't work for you.

**Comment by whitecolor** [comment]
Will close it for now.
